In [3]:
print("Rohit : Date : 4-3-2024 Pratical 1")
#ctrl enter or alt enter

Rohit


# Numpy Library.
diffrenece between paython list and numpy array

In [4]:
l1=[1,2,3]
l2=[5,4,6]

In [5]:
l1+l2

[1, 2, 3, 5, 4, 6]

## create using numpy library.
step 1- import numpy library (pyhon is oop)

In [6]:
import numpy as np

In [11]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [13]:
a

array([1, 2, 3])

In [16]:
b

array([4, 5, 6])

In [18]:
a+b

array([5, 7, 9])

In [22]:
l=range(1000)

In [25]:
import sys
# geting size of an array
print(sys.getsizeof(5)*len(l)) 

28000


In [27]:
arr=np.arange(1000)
#arr.size = return size of total array
#arr.itemsize = return size of singal element
print(arr.size*arr.itemsize)

4000


##predefined methods to create numpy array
1. arange
2. linespace
3. zeros
4. ones
5. random

In [30]:
#it will create numerical integer type data
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(10,dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
# create array without arange
arr=np.array([10,20,30])

In [36]:
arr

array([10, 20, 30])

In [38]:
arr[2]

30

In [40]:
#ndim is used to find dimension of array
a.ndim

1

In [43]:
#itemsize is used to return size of each element(int therefor 4 bytes)
a.itemsize

4

In [45]:
a.size

3

In [48]:
arr2=np.array([50,60,40],dtype=float)

In [53]:
#flaot take (8 bytes)
arr2.itemsize 

8

In [54]:
arr2.size

3

# Two Dimensional Array

In [58]:
arr3=np.array([[1,2,3],[4,5,6]])

In [60]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
arr3.ndim

2

In [65]:
arr3.size

6

In [68]:
arr4=np.array([[10,20,30],[40,50,60]],dtype=float)

In [70]:
arr4.itemsize

8

In [72]:
arr4.size

6

In [74]:
arr4.dtype

dtype('float64')

## Thee Dimensional Array

In [79]:
#np.linspace(startno,endno,how many no. generate betweem start and end no.)
np.linspace(1,10) 

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [81]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [84]:
arr4.shape #row,col

(2, 3)

In [86]:
arr4.reshape(3,2)

array([[10., 20.],
       [30., 40.],
       [50., 60.]])

In [87]:
arr4 #original data change nahi hota.

array([[10., 20., 30.],
       [40., 50., 60.]])